"""TTS 语言映射（自动生成，请勿手动编辑）。

由 服务端/Tools/generate_common_language_maps.py 根据
服务端/TTS/all_tts_languages.py 中 ALL_TTS_LANGUAGE_MAP 自动生成。
"""

ALL_TTS_LANGUAGE_MAP = {
    'aae': 'Arbëreshë Albanian',
    'aal': 'Afade',
    'aao': 'Algerian Saharan Arabic',
    'ab': 'Abkhazian',
    'abb': 'Bankon',
    'abn': 'Abua',
    'abr': 'Abron',
    'abs': 'Ambonese Malay',
    'abv': 'Baharna Arabic',
    'acm': 'Mesopotamian Arabic',
    'acw': 'Hijazi Arabic',
    'acx': 'Omani Arabic',
    'adf': 'Dhofari Arabic',
    'adx': 'Amdo Tibetan',
    'ady': 'Adyghe',
    'aeb': 'Tunisian Arabic',
    'aec': 'Saidi Arabic',
    'af': 'Afrikaans',
    'afb': 'Gulf Arabic',
    'afo': 'Eloyi',
    'ahl': 'Igo',
    'ahs': 'Ashe',
    'ajg': 'Aja (Benin)',
    'aju': 'Judeo-Moroccan Arabic',
    'ala': 'Alago',
    'aln': 'Gheg Albanian',
    'alo': 'Larike-Wakasihu',
    'am': 'Amharic',
    'amu': 'Guerrero Amuzgo',
    'an': 'Aragonese',
    'anc': 'Ngas',
    'ank': 'Goemai',
    'anp': 'Angika',
    'anw': 'Anaang',
    'aom': 'Ömie',
    'apc': 'Levantine Arabic',
    'apd': 'Sudanese Arabic',
    'ar': 'Arabic',
    'arb': 'Standard Arabic',
    'arq': 'Algerian Arabic',
    'ars': 'Najdi Arabic',
    'ary': 'Moroccan Arabic',
    'arz': 'Egyptian Arabic',
    'as': 'Assamese',
    'ast': 'Asturian',
    'avl': 'Eastern Egyptian Bedawi Arabic',
    'awo': 'Awak',
    'ayl': 'Libyan Arabic',
    'ayp': 'North Mesopotamian Arabic',
    'az': 'Azerbaijani',
    'ba': 'Bashkir',
    'bag': 'Tuki',
    'bas': 'Basa (Cameroon)',
    'bax': 'Bamun',
    'bba': 'Baatonum',
    'bbj': "Ghomálá'",
    'bbl': 'Bats',
    'bbu': 'Kulung (Nigeria)',
    'bce': 'Bamenyam',
    'bci': 'Baoulé',
    'bcs': 'Kohumono',
    'bcy': 'Bacama',
    'bda': 'Bayot',
    'bde': 'Bade',
    'bdm': 'Buduma',
    'be': 'Belarusian',
    'beb': 'Bebele',
    'bew': 'Betawi',
    'bfd': 'Bafut',
    'bft': 'Balti',
    'bg': 'Bulgarian',
    'bgp': 'Eastern Balochi',
    'bhb': 'Bhili',
    'bhh': 'Bukharic',
    'bho': 'Bhojpuri',
    'bhp': 'Bima',
    'bhr': 'Bara Malagasy',
    'bjj': 'Kanauji',
    'bjk': 'Barok',
    'bjn': 'Banjar',
    'bjt': 'Balanta-Ganja',
    'bkh': 'Bakoko',
    'bkm': 'Kom (Cameroon)',
    'bky': 'Bokyi',
    'bmm': 'Northern Betsimisaraka Malagasy',
    'bmq': 'Bomu',
    'bn': 'Bengali',
    'bnm': 'Batanga',
    'bnn': 'Bunun',
    'bns': 'Bundeli',
    'bo': 'Tibetan',
    'bou': 'Bondei',
    'bqg': 'Bago-Kusuntu',
    'br': 'Breton',
    'bra': 'Braj',
    'brh': 'Brahui',
    'bri': 'Mokpwe',
    'brx': 'Bodo',
    'bs': 'Bosnian',
    'bsh': 'Kati',
    'bsj': 'Bangwinji',
    'bsk': 'Burushaski',
    'btm': 'Batak Mandailing',
    'btv': 'Bateri',
    'bug': 'Buginese',
    'bum': 'Bulu (Cameroon)',
    'buo': 'Terei',
    'bux': 'Boghom',
    'bwr': 'Bura-Pabir',
    'bxf': 'Bilur',
    'byc': 'Ubaghara',
    'bys': 'Burak',
    'byv': 'Medumba',
    'byx': 'Qaqet',
    'bzc': 'Southern Betsimisaraka Malagasy',
    'bzw': 'Basa (Nigeria)',
    'ca': 'Catalan',
    'ccg': 'Samba Daka',
    'ceb': 'Cebuano',
    'cen': 'Cen',
    'cfa': 'Dijim-Bwilim',
    'cgg': 'Chiga',
    'chq': 'Quiotepec Chinantec',
    'cjk': 'Chokwe',
    'ckb': 'Central Kurdish',
    'ckl': 'Cibak',
    'ckr': 'Kairak',
    'cky': 'Cakfem-Mushere',
    'cnh': 'Hakha Chin',
    'cpy': 'South Ucayali Ashéninka',
    'cs': 'Czech',
    'cte': 'Tepinapa Chinantec',
    'ctl': 'Tlacoatzintepec Chinantec',
    'cut': 'Teutila Cuicatec',
    'cux': 'Tepeuxila Cuicatec',
    'cv': 'Chuvash',
    'cy': 'Welsh',
    'da': 'Danish',
    'dag': 'Dagbani',
    'dar': 'Dargwa',
    'dav': 'Taita',
    'dbd': 'Dadiya',
    'dcc': 'Deccan',
    'de': 'German',
    'deg': 'Degema',
    'dgh': 'Dghwede',
    'dgo': 'Dogri',
    'dje': 'Zarma',
    'dmk': 'Domaaki',
    'dml': 'Dameli',
    'dru': 'Rukai',
    'dty': 'Dotyali',
    'dua': 'Duala',
    'dv': 'Dhivehi',
    'dyu': 'Dyula',
    'dzg': 'Dazaga',
    'ebr': 'Ebrié',
    'ebu': 'Embu',
    'ego': 'Eggon',
    'eiv': 'Askopan',
    'eko': 'Koti',
    'ekr': 'Yace',
    'el': 'Greek',
    'elm': 'Eleme',
    'en': 'English',
    'eo': 'Esperanto',
    'es': 'Spanish',
    'esu': 'Central Yupik',
    'et': 'Estonian',
    'eto': 'Eton (Cameroon)',
    'ets': 'Yekhee',
    'etu': 'Ejagham',
    'eu': 'Basque',
    'ewo': 'Ewondo',
    'ext': 'Extremaduran',
    'eyo': 'Keiyo',
    'fa': 'Persian',
    'fan': 'Fang (Equatorial Guinea)',
    'fat': 'Fanti',
    'ff': 'Fulah',
    'ffm': 'Maasina Fulfulde',
    'fi': 'Finnish',
    'fia': 'Nobiin',
    'fil': 'Filipino',
    'fip': 'Fipa',
    'fkk': 'Kirya-Konzəl',
    'fmp': "Fe'fe'",
    'fo': 'Faroese',
    'fr': 'French',
    'fub': 'Adamawa Fulfulde',
    'fuc': 'Pulaar',
    'fue': 'Borgu Fulfulde',
    'fuf': 'Pular',
    'fuh': 'Western Niger Fulfulde',
    'fui': 'Bagirmi Fulfulde',
    'fuq': 'Central-Eastern Niger Fulfulde',
    'fuv': 'Nigerian Fulfulde',
    'fy': 'Western Frisian',
    'ga': 'Irish',
    'gbm': 'Garhwali',
    'gbr': 'Gbagyi',
    'gby': 'Gbari',
    'gcc': 'Mali',
    'gdf': 'Guduf-Gava',
    'gej': 'Gen',
    'ges': 'Geser-Gorom',
    'ggg': 'Gurgula',
    'gid': 'Gidar',
    'gig': 'Goaria',
    'giz': 'South Giziga',
    'gjk': 'Kachi Koli',
    'gju': 'Gujari',
    'gl': 'Galician',
    'glw': 'Glavda',
    'gn': 'Guarani',
    'gol': 'Gola',
    'gom': 'Goan Konkani',
    'gsl': 'Gusilay',
    'gu': 'Gujarati',
    'gui': 'Eastern Bolivian Guaraní',
    'gur': 'Farefare',
    'guz': 'Gusii',
    'gv': 'Manx',
    'gwc': 'Gawri',
    'gwe': 'Gweno',
    'gwt': 'Gawar-Bati',
    'gya': 'Northwest Gbaya',
    'gyz': 'Geji',
    'ha': 'Hausa',
    'hah': 'Hahon',
    'hao': 'Hakö',
    'haw': 'Hawaiian',
    'haz': 'Hazaragi',
    'hbb': 'Huba',
    'he': 'Hebrew',
    'hem': 'Hemba',
    'hi': 'Hindi',
    'hia': 'Lamang',
    'hkk': 'Hunjara-Kaina Ke',
    'hla': 'Halia',
    'hno': 'Northern Hindko',
    'hoj': 'Hadothi',
    'hr': 'Croatian',
    'hsb': 'Upper Sorbian',
    'ht': 'Haitian',
    'hu': 'Hungarian',
    'hue': 'San Francisco Del Mar Huave',
    'hul': 'Hula',
    'hux': 'Nüpode Huitoto',
    'hwo': 'Hwana',
    'hy': 'Armenian',
    'hz': 'Herero',
    'ia': 'Interlingua (International Auxiliary Language Association)',
    'ibb': 'Ibibio',
    'id': 'Indonesian',
    'ida': 'Idakho-Isukha-Tiriki',
    'idu': 'Idoma',
    'ig': 'Igbo',
    'ijc': 'Izon',
    'ijn': 'Kalabari',
    'ik': 'Inupiaq',
    'ikw': 'Ikwere',
    'is': 'Icelandic',
    'ish': 'Esan',
    'iso': 'Isoko',
    'it': 'Italian',
    'its': 'Isekiri',
    'itw': 'Ito',
    'itz': 'Itzá',
    'ja': 'Japanese',
    'jal': 'Yalahatan',
    'jax': 'Jambi Malay',
    'jgo': 'Ngomba',
    'jmx': 'Western Juxtlahuaca Mixtec',
    'jns': 'Jaunsari',
    'jqr': 'Jaqaru',
    'juk': 'Wapan',
    'juo': 'Jiba',
    'jv': 'Javanese',
    'jw': 'Javanese',
    'ka': 'Georgian',
    'kab': 'Kabyle',
    'kai': 'Karekare',
    'kaj': 'Jju',
    'kam': 'Kamba',
    'kbd': 'Kabardian',
    'kbl': 'Kanembu',
    'kbt': 'Abadi',
    'kcq': 'Kamo',
    'kdh': 'Tem',
    'kea': 'Kabuverdianu',
    'keu': 'Akebu',
    'kfe': 'Kota (India)',
    'kfk': 'Kinnauri',
    'kfp': 'Korwa',
    'khg': 'Khams Tibetan',
    'khw': 'Khowar',
    'kj': 'Kuanyama',
    'kjc': 'Coastal Konjo',
    'kjk': 'Highland Konjo',
    'kk': 'Kazakh',
    'kln': 'Kalenjin',
    'kls': 'Kalasha',
    'km': 'Khmer',
    'kmr': 'Northern Kurdish',
    'kmy': 'Koma',
    'kn': 'Kannada',
    'kna': 'Dera (Nigeria)',
    'knn': 'Konkani',
    'ko': 'Korean',
    'kol': 'Kol (Papua New Guinea)',
    'koo': 'Konzo',
    'kpo': 'Ikposo',
    'kqo': 'Eastern Krahn',
    'ks': 'Kashmiri',
    'ksd': 'Kuanua',
    'ksf': 'Bafia',
    'kto': 'Kuot',
    'kuh': 'Kushi',
    'kvx': 'Parkari Koli',
    'kw': 'Cornish',
    'kwm': 'Kwambi',
    'kxp': 'Wadiyara Koli',
    'ky': 'Kirghiz',
    'kyx': 'Rapoisi',
    'la': 'Latin',
    'lag': 'Rangi',
    'lb': 'Luxembourgish',
    'lcm': 'Tungag',
    'ldb': 'Dũya',
    'lg': 'Ganda',
    'lij': 'Ligurian',
    'lir': 'Liberian English',
    'lkb': 'Kabras',
    'lla': 'Lala-Roba',
    'ln': 'Lingala',
    'lnu': 'Longuda',
    'lo': 'Lao',
    'loa': 'Loloda',
    'lrk': 'Loarki',
    'lss': 'Lasi',
    'lt': 'Lithuanian',
    'ltg': 'Latgalian',
    'lto': 'Tsotso',
    'lua': 'Luba-Lulua',
    'luo': 'Luo',
    'lus': 'Lushai',
    'lv': 'Latvian',
    'lwg': 'Wanga',
    'mab': 'Yutanduchi Mixtec',
    'maf': 'Mafa',
    'mai': 'Maithili',
    'mau': 'Huautla Mazatec',
    'max': 'North Moluccan Malay',
    'mbo': 'Mbo (Cameroon)',
    'mcf': 'Matsés',
    'mcn': 'Masana',
    'mcx': 'Mpiemo',
    'mdd': 'Mbum',
    'mde': 'Maba (Chad)',
    'mdf': 'Moksha',
    'mek': 'Mekeo',
    'mer': 'Meru',
    'meu': 'Motu',
    'mfm': 'Marghi South',
    'mfn': 'Cross River Mbembe',
    'mfo': 'Mbe',
    'mfv': 'Mandjak',
    'mgg': 'Mpumpong',
    'mgi': 'Lijili',
    'mhk': 'Mungaka',
    'mhr': 'Eastern Mari',
    'mi': 'Maori',
    'mig': 'San Miguel El Grande Mixtec',
    'miu': 'Cacaloxtepec Mixtec',
    'mk': 'Macedonian',
    'mkf': 'Miya',
    'mki': 'Dhatki',
    'ml': 'Malayalam',
    'mlq': 'Western Maninkakan',
    'mn': 'Mongolian',
    'mne': 'Naba',
    'mni': 'Manipuri',
    'mqy': 'Manggarai',
    'mr': 'Marathi',
    'mrj': 'Western Mari',
    'mrr': 'Maria (India)',
    'mrt': 'Marghi Central',
    'ms': 'Malay',
    'mse': 'Musey',
    'msh': 'Masikoro Malagasy',
    'msw': 'Mansoanka',
    'mt': 'Maltese',
    'mtr': 'Mewari',
    'mtu': 'Tututepec Mixtec',
    'mtx': 'Tidaá Mixtec',
    'mua': 'Mundang',
    'mug': 'Musgu',
    'mui': 'Musi',
    'mve': 'Marwari (Pakistan)',
    'mvy': 'Indus Kohistani',
    'mxs': 'Huitepec Mixtec',
    'mxu': 'Mada (Cameroon)',
    'mxy': 'Southeastern Nochixtlán Mixtec',
    'my': 'Burmese',
    'myv': 'Erzya',
    'mzl': 'Mazatlán Mixe',
    'nal': 'Nalik',
    'nan': 'Min Nan Chinese',
    'nap': 'Neapolitan',
    'nb': 'Norwegian',
    'nbh': 'Ngamo',
    'ncf': 'Notsi',
    'nco': 'Sibe',
    'ncx': 'Central Puebla Nahuatl',
    'ndi': 'Samba Leko',
    'ne': 'Nepali',
    'ng': 'Ndonga',
    'ngi': 'Ngizim',
    'nhg': 'Tetelcingo Nahuatl',
    'nhi': 'Zacatlán-Ahuacatlán-Tepetzintla Nahuatl',
    'nhn': 'Central Nahuatl',
    'nhq': 'Huaxcaleca Nahuatl',
    'nja': 'Nzanyi',
    'nl': 'Dutch',
    'nla': 'Ngombale',
    'nlv': 'Orizaba Nahuatl',
    'nmg': 'Kwasio',
    'nmz': 'Nawdm',
    'nn': 'Norwegian',
    'nnh': 'Ngiemboon',
    'no': 'Norwegian',
    'noe': 'Nimadi',
    'npi': 'Nepali',
    'nso': 'Pedi',
    'ny': 'Chichewa',
    'nyu': 'Nyungwe',
    'oc': 'Occitan',
    'odk': 'Od',
    'odu': 'Odual',
    'ogo': 'Khana',
    'om': 'Oromo',
    'orc': 'Orma',
    'oru': 'Ormuri',
    'ory': 'Odia',
    'os': 'Iron Ossetic',
    'pa': 'Panjabi',
    'pbs': 'Central Pame',
    'pbt': 'Southern Pashto',
    'pbu': 'Northern Pashto',
    'pcm': 'Nigerian Pidgin',
    'pex': 'Petats',
    'phl': 'Phalura',
    'phr': 'Pahari-Potwari',
    'pip': 'Pero',
    'piy': 'Piya-Kwonci',
    'pko': 'Pökoot',
    'pl': 'Polish',
    'plk': 'Kohistani Shina',
    'plt': 'Plateau Malagasy',
    'pmq': 'Northern Pame',
    'pms': 'Piemontese',
    'pmy': 'Papuan Malay',
    'pnb': 'Western Panjabi',
    'poc': 'Poqomam',
    'poe': 'San Juan Atzingo Popoloca',
    'pow': 'San Felipe Otlaltepec Popoloca',
    'prq': 'Ashéninka Perené',
    'ps': 'Pushto',
    'pst': 'Central Pashto',
    'pt': 'Portuguese',
    'pua': 'Western Highland Purepecha',
    'pwn': 'Paiwan',
    'qug': 'Chimborazo Highland Quichua',
    'qum': 'Sipacapense',
    'qup': 'Southern Pastaza Quechua',
    'qur': 'Yanahuanca Pasco Quechua',
    'qus': 'Santiago del Estero Quichua',
    'quv': 'Sacapulteco',
    'qux': 'Yauyos Quechua',
    'quy': 'Ayacucho Quechua',
    'qva': 'Ambo-Pasco Quechua',
    'qvi': 'Imbabura Highland Quichua',
    'qvj': 'Loja Highland Quichua',
    'qvl': 'Cajatambo North Lima Quechua',
    'qwa': 'Corongo Ancash Quechua',
    'qws': 'Sihuas Ancash Quechua',
    'qxa': 'Chiquián Ancash Quechua',
    'qxp': 'Puno Quechua',
    'qxt': 'Santa Ana de Tusi Pasco Quechua',
    'qxu': 'Arequipa-La Unión Quechua',
    'qxw': 'Jauja Wanca Quechua',
    'rag': 'Logooli',
    'rm': 'Romansh',
    'ro': 'Romanian',
    'rob': "Tae'",
    'rof': 'Rombo',
    'roo': 'Rotokas',
    'rth': 'Ratahan',
    'ru': 'Russian',
    'rup': 'Macedo-Romanian',
    'rw': 'Kinyarwanda',
    'sa': 'Sanskrit',
    'sah': 'Yakut',
    'sat': 'Santali',
    'sau': 'Saleman',
    'say': 'Saya',
    'sbn': 'Sindhi Bhil',
    'sc': 'Sardinian',
    'scl': 'Shina',
    'scn': 'Sicilian',
    'sd': 'Sindhi',
    'sei': 'Seri',
    'shu': 'Chadian Arabic',
    'si': 'Sinhala',
    'sip': 'Sikkimese',
    'siw': 'Siwai',
    'sjr': 'Siar-Lak',
    'sk': 'Slovak',
    'skg': 'Sakalava Malagasy',
    'skr': 'Saraiki',
    'sl': 'Slovenian',
    'sn': 'Shona',
    'snc': 'Sinaugoro',
    'snk': 'Soninke',
    'so': 'Somali',
    'sol': 'Solos',
    'sps': 'Saposa',
    'sq': 'Albanian',
    'sr': 'Serbian',
    'src': 'Logudorese Sardinian',
    'sro': 'Campidanese Sardinian',
    'ssi': 'Sansi',
    'ste': 'Liana-Seti',
    'sua': 'Sulka',
    'sv': 'Swedish',
    'sva': 'Svan',
    'sw': 'Swahili',
    'szy': 'Sakizaya',
    'ta': 'Tamil',
    'tan': 'Tangale',
    'tar': 'Central Tarahumara',
    'tay': 'Atayal',
    'tbf': 'Mandara',
    'tcf': "Malinaltepec Me'phaa",
    'tcy': 'Tulu',
    'tdn': 'Tondano',
    'tdx': 'Tandroy-Mahafaly Malagasy',
    'te': 'Telugu',
    'tg': 'Tajik',
    'tgc': 'Tigak',
    'th': 'Thai',
    'the': 'Chitwania Tharu',
    'thq': 'Kochila Tharu',
    'thr': 'Rana Tharu',
    'thv': 'Tahaggart Tamahaq',
    'ti': 'Tigrinya',
    'tig': 'Tigre',
    'tio': 'Teop',
    'tk': 'Turkmen',
    'tkg': 'Tesaka Malagasy',
    'tkt': 'Kathoriya Tharu',
    'tl': 'Filipino',
    'tli': 'Tlingit',
    'tlp': 'Filomena Mata-Coahuitlán Totonac',
    'tn': 'Tswana',
    'tok': 'Toki Pona',
    'tpl': "Tlacoapa Me'phaa",
    'tpz': 'Tinputz',
    'tqp': 'Tomoip',
    'tr': 'Turkish',
    'trp': 'Kok Borok',
    'trq': 'San Martín Itunyoso Triqui',
    'trv': 'Sediq',
    'trw': 'Torwali',
    'tt': 'Tatar',
    'ttj': 'Tooro',
    'ttr': 'Tera',
    'ttu': 'Torau',
    'tui': 'Tupuri',
    'tul': 'Tula',
    'tuq': 'Tedaga',
    'tuv': 'Turkana',
    'tuy': 'Tugen',
    'tvo': 'Tidore',
    'tvu': 'Tunen',
    'tw': 'Twi',
    'twu': 'Termanu',
    'txs': 'Tonsea',
    'txy': 'Tanosy Malagasy',
    'udl': 'Wuzlam',
    'ug': 'Uighur',
    'uk': 'Ukrainian',
    'uki': 'Kui (India)',
    'umb': 'Umbundu',
    'ur': 'Urdu',
    'ush': 'Ushojo',
    'uz': 'Uzbek',
    'uzn': 'Northern Uzbek',
    'vai': 'Vai',
    'var': 'Huarijio',
    'ver': 'Mom Jango',
    'vi': 'Vietnamese',
    'vmc': 'Juxtlahuaca Mixtec',
    'vmj': 'Ixtayutla Mixtec',
    'vmm': 'Mitlatongo Mixtec',
    'vmp': 'Soyaltepec Mazatec',
    'vmz': 'Mazatlán Mazatec',
    'vot': 'Votic',
    'vro': 'Võro',
    'wbl': 'Wakhi',
    'wci': 'Waci Gbe',
    'weo': 'Wemale',
    'wes': 'Cameroon Pidgin',
    'wja': 'Waja',
    'wji': 'Warji',
    'wo': 'Wolof',
    'wof': 'Gambian Wolof',
    'xh': 'Xhosa',
    'xhe': 'Khetrani',
    'xka': 'Kalkoti',
    'xmf': 'Mingrelian',
    'xmv': 'Antankarana Malagasy',
    'xmw': 'Tsimihety Malagasy',
    'xpe': 'Liberia Kpelle',
    'xti': 'Sinicahua Mixtec',
    'xtu': 'Cuyamecalco Mixtec',
    'yaq': 'Yaqui',
    'yav': 'Yangben',
    'yay': 'Agwagwune',
    'ydd': 'Eastern Yiddish',
    'ydg': 'Yidgha',
    'yer': 'Tarok',
    'yes': 'Nyankpa',
    'yi': 'Yiddish',
    'yo': 'Yoruba',
    'yue': 'Cantonese',
    'zga': 'Kinga',
    'zgh': 'Standard Moroccan Tamazight',
    'zh': 'Chinese',
    'zh-cn': 'Chinese',
    'zh-tw': 'Chinese',
    'zoc': 'Copainalá Zoque',
    'zoh': 'Chimalapa Zoque',
    'zor': 'Rayón Zoque',
    'zpv': 'Chichicapan Zapotec',
    'zpy': 'Mazaltepec Zapotec',
    'ztg': 'Xanaguía Zapotec',
    'ztn': 'Santa Catarina Albarradas Zapotec',
    'ztp': 'Loxicha Zapotec',
    'zts': 'Tilquiapan Zapotec',
    'ztu': 'Güilá Zapotec',
    'zu': 'Zulu',
    'zza': 'Zaza',
}

ALL_TTS_LANGUAGE_CODES = sorted(ALL_TTS_LANGUAGE_MAP.keys())
